---
title: "Compare ddl and psmsl"
author: "Willem Stolte, Nathalie Dees"
date: "2024-09-12"
output:
  html_document:
    df_print: paged
    code_folding: hide
---

```{r setupWind}
knitr::opts_chunk$set(
  echo = TRUE,
  comment=FALSE,
  message=FALSE,
  warning = FALSE
)
```

```{r dependencies}
require(tidyverse)
list.files()
source("../../analysis/sealevelmonitor/_common/functions.R")
source("../../analysis/sealevelmonitor/_common/plotfunctions.R")
mainstations_df <- readMainStationInfo(filepath = "../../")
```

```{r}

list.files("../../analysis")
config <- RcppTOML::parseToml("../../analysis/sealevelmonitor/_common/configuration.TOML")
source("../../analysis/sealevelmonitor/_common/functions.R")
source("../../analysis/sealevelmonitor/_common/plotfunctions.R")

epoch = config$constants$epoch

df_psmsl <- readSeaLevelData(file.path("../../data/deltares/results/dutch-sea-level-monitor-export-stations-2023-11-20.csv"))


ddl_y_files <- list.files("../../data/rijkswaterstaat/ddl/annual_means", full.names = T)

ddl_y_means <- lapply(ddl_y_files, function(x) read_delim(x, delim = ";", col_types = cols())) %>%
  list_rbind() %>%
  filter(annual_mean_mm_corrected > -1000)


```


```{r, fig.width=8, fig.height=3}
ddl_y_means %>%
  filter(
    locatie.naam %in% mainstations_df$name,
    # year > 1986,
    groepering.code == "NVT"
  ) %>%
ggplot(aes(x = year)) +
  geom_col(aes(y = n/1e3, fill = locatie.naam), position = position_dodge())# +
  # coord_cartesian(xlim = c(1987, 1995))
```

```{r}
ddl_y_means %>%
  filter(
    locatie.naam %in% mainstations_df$name,
    year > 1986,
    groepering.code == "NVT"
  ) %>%
  ggplot(aes(year,annual_mean_mm_corrected)) +
  geom_line(aes(color = locatie.naam), size = 1) +
  theme(legend.position = "bottom")
```

```{r}
ddl_y_means_av <- ddl_y_means %>%
    filter(
    locatie.naam %in% mainstations_df$name,
    groepering.code == "NVT"
  ) %>%
  bind_rows(
    . |>
      group_by(year) |>
      summarise(
        annual_mean_mm_corrected = mean(annual_mean_mm_corrected)
      ) |>
      mutate(
        locatie.naam = "Netherlands",
        source = "rws_ddl_mean"
      )
  ) %>%
  bind_rows(
    . |>
      filter(locatie.naam %in% c("Vlissingen", "Hoek van Holland", "Den Helder", "Harlingen", "IJmuiden")) |>
      group_by(year) |>
      summarise(
        annual_mean_mm_corrected = mean(annual_mean_mm_corrected)
      ) |>
      mutate(
        locatie.naam = "Netherlands (without Delfzijl)",
        source = "rws_ddl_mean"
      )
  )

```

```{r}

ddl_y_means_av %>%
  ggplot(aes(x = year)) +
  geom_point(aes(y = annual_mean_mm_corrected, color = locatie.naam))

ddl_y_means_av %>%
  select(
    year, 
    height = annual_mean_mm_corrected, 
    station = locatie.naam, 
    source
    ) %>%
  bind_rows(
    df_psmsl %>% 
      select(
        year, 
        height, 
        station) %>%
      mutate(source = "psmsl")) %>%
  # filter(station == "Netherlands (without Delfzijl)") %>%
  filter(year > 1900 & year < 2023) %>%
  ggplot(aes(year, height)) +
  geom_point(aes(shape = source, color = source), size = 1) +
  # geom_smooth(method = "lm", aes(color = source), alpha = 0) +
  coord_cartesian(xlim = c(1900, NA)) +
  facet_wrap("station")

ddl_y_means_av %>%
  select(
    year, 
    height_ddl = annual_mean_mm_corrected, 
    station = locatie.naam
    ) %>%
  left_join(
    df_psmsl %>% 
      select(
        year, 
        height_psmsl = height, 
        station)
    ) %>%
  # filter(station == "Netherlands (without Delfzijl)") %>%
  filter(year > 1900 & year < 2023) %>%
  ggplot(aes(year, height_ddl)) +
  geom_point(aes(color = "ddl"), size = 2, shape = 21, fill = "transparent") +
  geom_point(aes(y = height_psmsl, color = "psmsl"), size = 1) +
  # geom_smooth(method = "lm", aes(color = source), alpha = 0) +
  coord_cartesian(xlim = c(1900, NA)) +
  facet_wrap("station")

```


