---
acronyms:
  insert_loa: false
  loa_title: "Lijst met afkortingen"
  insert_links: false
  fromfile:
    - acronyms.yml
---

# Resultaten {#resultaten}

## Voorkeursmodel


## Huidige zeespiegel(stijging) {#huidige}


## Bodemdaling en zeespiegelstijging
Bij alle getijdenstations bestaat het gemeten relatieve zeespiegelstijgingssignaal voor een deel uit lange-termijn geologische bodemdaling [@Hijma2025b]. Deze daling wordt hoofdzakelijk veroorzaakt door tektonische en glacio-isostatische bodemdaling en heeft dalingssnelheden die van zuid naar noord toenemen van circa 2 naar 5 cm/eeuw (@fig-totgeol100yr). De metingen worden hier niet voor gecorrigeerd en de via PSMSL beschikbare zeespiegeldata omvatten dus deze lange-termijn geologische bodemdalingscomponent.

![Geologische bodemdaling per 100 jaar [@Hijma2025b]](images/Totgeol100yr_nieuw.png){#fig-totgeol100yr width=80%}

Er zijn twee stations waar ook bodemdaling door gaswinning heeft plaatsgevonden, namelijk Hoek van Holland en Delfzijl. Bij Hoek van Holland gaat het om minder dan 2 cm in de laatste decennia en gaan we er vanuit dat deze daling in het zeespiegelsignaal zit. De verwachte daling door gaswinning in de komende decennia is minder dan 1 cm [@Hijma2026]. De daling bij Delfzijl is veel groter geweest en bedraagt ongeveer 30 cm sinds 1963. Voor Delfzijl weten we vrij zeker dat de bodemdaling sinds 1973 niet in de zeespiegeldata zit, maar dat de metingen gecorrigeerd worden [@Jong1973, punt 5]. Dit betekent dat de relatieve zeespiegelstijging bij Delfzijl eigenlijk sneller gaat dan in PSMSL gepubliceerd wordt, omdat de daling door gaswinning niet meegenomen wordt. Tussen de start van de gaswinning in Groningen in 1963 en 1973 daalde de bodem bij Delfzijl ongeveer 7 cm. Wij gaan er hier vanuit dat deze daling op dezelfde manier is behandeld als de daling na 1973, conform [@Jong1973, punt 5], en dus niet in het zeespiegelsignaal zit. Door het dichtdraaien van de gaskraan is de daling bij het station sterk afgenomen en naar verwachting zal deze nog slechts enkele centimeters bedragen in de komende decennia [@Hijma2026].

Station Harlingen wordt waarschijnlijk al enigszins beïnvloed door bodemdaling door zoutwinning, al is de gemodelleerde invloed momenteel nog zeer gering en van recente datum. De zoutwinning vindt plaats op de Waddenzee ten westen van Harlingen en naar verwachting zal hierdoor de komende 30 jaar een aantal centimeter bodemdaling optreden bij Harlingen [@Hijma2025c; @Hijma2026]. De onzekerheid is echter groot en een kleine verschuiving in de vorm of positie van de bodemdalingsschotel kan resulteren in geen extra bodemdaling of juist nog enkele centimeters meer. De extra bodemdaling wordt gemonitord, waardoor een eventuele impact op de zeespiegelmetingen goed in beeld zal komen.

Bij de meeste stations is de totale bodemdaling dus gelijk aan de geologische bodemdaling, maar bij enkele stations is de totale bodemdaling een optelsom van de geologische bodemdaling en de daling door delfstofwinning. @tbl-bodemdalingscomponenten geeft per station de verschillende bodemdalingscomponenten, de gemeten relatieve zeespiegelstijging en de afgeleide absolute zeespiegelstijging. @fig-totdaling100yr geeft een ruimtelijk beeld van de gecombineerde bodemdaling door geologische bodemdaling en daling door winning. 

|station|Geologische bodemdaling (mm/jaar)|Daling door winning (mm/jaar)|Totale bodemdaling (mm/jaar)|Huidige relatieve ZSS (mm/jaar)|Huidige absolute ZSS (mm/jaar)
|-|-|-|-|-|-|
|Vlissingen|0.23 (0.18-0.29)|0|0.23 (0.18-0.29)|???|????|
|Hoek van Holland|0.33 (0.30-0.39)|0.20 (0.15-0.25) |0.53 (0.46-0.60)|???|???|
|IJmuiden|0.40 (0.36-0.45)|0|0.40 (0.36-0.45)|???|???|
|Den Helder|0.47 (0.43-0.51|0|0.47 (0.43-0.51)|???|???|
|Harlingen|0.51 (0.46-0.57)|0.20 (0.15-0.25)|0.71 (0.64-0.78)|???|???|
|Delfzijl|0.38 (0.34-0.45)|3.95 (2.96-4.94)|0.38 (0.34-0.45)|???|???|
: Uitsplitsing bodemdaling [op basis van @Hijma2025b and @Hijma2026] en zeespiegelstijging per station (dit rapport). Geologische bodemdaling is constant op tijdschalen van eeuwen, de dalingssnelheid door winning is berekend voor de periode 1996-2025. De totale bodemdaling bij Hoek van Holland is inclusief daling door winning, bij Delfzijl exclusief daling door winning (zie tekst). De gemiddelde relatieve zeespiegelstijging is gemeten over de periode xxx (gebroken lineair model). Het 66%-betrouwbaarheidsinterval staat tussen haakjes vermeld. {#tbl-bodemdalingscomponenten}


![Totale bodemdaling in het kustgebied in de laatste 100 jaar [@Hijma2026]](images/Totaledaling1926_2025.png){#fig-totdaling100yr width=80%}

## Vergelijking met scenarios (KNMI)


## Vergelijking met zeespiegelbudgetten


## Variatie binnen Nederland


## Vergelijking? met satellietmetingen
