project:
  type: book

execute: 
  echo: false
  warning: false
  message: false
  freeze: auto

book:
  title: "Zeespiegelmonitor 2026"
  author: "Willem Stolte, Dewi Lebars, Dorien Honingh, Nathalie Dees, Marc Hijma, Martin Verlaan"
  date: today
  page-navigation: true
  favicon: assets/icon-deltares.svg
  page-footer: 
    background: "#2E89BF"
    center: Zeespiegelmonitor 2026
  sidebar:
    footer: custom-component/sidebar-footer.html
  navbar: 
    background: "#2E89BF"
    pinned: true
  chapters:
    - index.qmd
    - samenvatting.qmd
    - 01_inleiding.qmd
    # - 015_zeespiegelaspecten.qmd
    - 02_methodiek.qmd
    - 03_resultaten.qmd
    - 04_discussie.qmd
    - 05_literatuur.qmd
  appendices:
    - 06_appendix_A.qmd
    - 07_appendix_B.qmd
    - 08_appendix_C.qmd
    - 09_appendix_D.qmd
    - 10_appendix_E.qmd
    - 11_appendix_F.qmd
  # abstract: 
  # description: "metadata for html version"
  # references: "references.bib"
  output-file: "Zeespiegelmonitor_2026"
#  delete_merged_file: true
#  before_chapter_script: _common.R
bibliography: 
  - bib/sealevel.bib
  - bib/dees.bib
  - bib/dewi.bib

link-citations: true

format:
  html:
    theme: cosmo
    lightbox: true
    css:
        - styles.css
        - draft.css
  # pdf:
  #   # documentclass: scrreprt
  #   fig-width: 6
  #   fig-height: 4
  #   template: deltares-report-template.tex
  #   # extra_dependencies: ["flafter"]
  #   include-in-header:
  #     - preamble.tex
  #   pdf-engine: pdflatex
  #   keep_tex: true
  #   # biblio-config: false
  #   cite-method: natbib   # natbib
  # # docx:
  # #   default
  
filters:
  - acronyms

acronyms:
  loa_title: "Lijst met afkortingen"
  insert_links: false
  id_prefix: "acronyms_"
  fromfile:
    - acronyms.yml

lang:
  nl


editor: source

