

# Waterwerken

Dit is een verzameling van informatie over de bouw van waterwerken. 

```{r}

library(tidyverse)
library(rvest)

```


## Deltawerken

Informatie van Wikipedia: 

```{r wikipediaDeltawerken}


url <-  "https://nl.wikipedia.org/wiki/Deltawerken"

df <- url %>% 
  read_html() %>% 
  html_nodes("table") %>% 
  html_table(fill = T) 

table_deltawerken <- data.frame(df[[1]]) %>%
  rename_all( .funs = list(tolower)) %>%
  separate("bouwperiode" , into = c("start", "end")) %>%
  mutate(regio = "zuidwestelijke delta")

```



```{r}
table_waddenzee <- tribble(
  ~project, ~start, ~end, ~functie, ~waterloop, ~plaats, 
  "Afsluitdijk", "1920", "1932", "Dam", "IJssel", "Nabij Harlingen",
  "Lauwersmeer", "1961", "1969", "Dam", "Lauwersmeer", "Nabij Lauwersoog",
  "Wieringermeer", "1924", "1930", "Polder", "", "Nabij Wieringen" 
) %>%
  mutate(regio = "Waddenzee")
```




```{r combine}
waterkeringen <- table_deltawerken %>% bind_rows(table_waddenzee) %>%
    mutate(start = as.integer(start), end = as.integer(end))

write_csv2(waterkeringen, file = "../../data/deltares/waterwerken.csv")

waterkeringen = read_csv2("../../data/deltares/waterwerken.csv")
```



```{r}
waterkeringen %>%
  filter(regio == "Waddenzee") %>%
  arrange(start) %>%
  ggplot(aes()) +
  geom_segment(aes(x = start, xend = end, y = as.factor(project)), color = "blue", linewidth = 4) +
  theme_minimal()
```




```{r}
waterkeringen %>%
  filter(regio == "Waddenzee") %>%
  mutate(start = as.integer(start), end = as.integer(end)) %>%
  ggplot(aes()) +
  geom_rect(aes(xmin = start, xmax = end, ymin = 0, ymax = 1, fill = project), alpha = 0.4) +
    geom_vline(aes(xintercept = end)) +
  geom_label(aes(x = end, label = project, y = 0.5), position = position_jitter(height = 0.5, width = 0), hjust = "right")
```


```{r}
waterkeringen %>%
  filter(regio == "Waddenzee") %>%
  ggplot(aes()) +
  geom_vline(aes(xintercept = end)) +
  geom_label(aes(x = end, label = project), y = 1)
```






