---
title: "Wadden"
format: html
---



## Narrative

In de Zeespiegelmonitor lijken de Waddenzeestations vanaf ongeveer 1990 sneller te stijgen dan de rest van Nederland. Als dit zo zou zijn dan heeft dat implicaties voor de schattingen vande stijging in de Zeespiegelmonitor. De getallen van de monitor zelf geven geen uitsluitsel hierover omdat er maar 3 stations in de Wadden worden meegenomen: Delfzijl, Den Helder en Harlingen. Hierbij moet worden opgemerkt dat er bij Delfzijl nog twijfels zijn ivm de correctie voor NAP. Van de overgebleven 2 lokaties ligt Den Helder dicht bij de kust en Harlingen diep in de Waddenzee. Hierdoor is er uiteindelijk te weinig informatie om direkt iets te kunnen zeggen over de ruimtelijken verdeling. 

Dit is de aanleiding om te onderzoeken of er met aanvullende metingen en begrip van de fysica meer gezegd kan worden over de ruimtelijke verdeling van de zeespiegelstijging in en rond de Waddenzee. Omdat de overige lokaties van mindere kwaliteit zijn en/of minder lange reeksen bevatten, zetten we in op een combinatie met modellering/fysica. Het doel is dat de steeds meerdere signalen zijn voordat er een conclusie wordt getrokken. Dat vermindert het risico dat er onterecht conclusies worden getrokken rind dit complexe vraagstuk.

Als de zeespiegel ongelijk stijgt binnen en buiten de Wadden, dan moet er een horizontaal verhang zijn. Dit kan alleen bestaan als er een kracht is, die dit veroorzaakt. De meest waarschijnlijke kandidaat is het getij. Dit betekent ook dat er hoogswaarschijnlijk veranderingen in het getij zijn, die met de zeespiegelstijging samen hangen. Dit is apart te controleren met metingen.

Om meer uit de bestaande metingen te halen zonder door dat de conclusies worden vervuilt door problemen met de metingen, willen we een techniek ontwikkelen die de ruimtelijke samenhang van de langzame zeespiegelvariatie gebruikt om de metingen met elkaar te vergelijken en zo de problemen op te sporen. Als extra controle voorzien we een discussie met de experts bij Rijkswaterstaat. Dit is ook in het verleden succesvol geweest. De combinatie van afwijkingen in de samenhang met een bevestiging vanuit het meetnet over een specifieke gebeurtenis, geeft vertrouwen dat er echt iets aan de hand was, zodat er niet ten onrechte data wordt weggegooid. Zo kan iteratief aan een grotere dataset worden gewerkt.

### Waarnemingen

1.	De zeespiegel in de Waddenzee lijkt tot begin 90-jaren achter te lopen bij de Hollandse kust. Daarna vind een versnelling plaats waardoor nu alle stations qua stijging ongeveer hetzelfde zijn. De gevonden “knik” of versnelling van de zeespiegel vanaf 1993 wordt daardoor geprononceerder. Dit rechtvaardigt de vraag of op zijn minst een deel van de versnelling door iets anders veroorzaakt wordt dan door “echte” zeespiegelstijging. (figuur 1)
2.	De westelijke Waddenzee is na de afsluiting van de Zuiderzee lange tijd niet in evenwicht geweest qua morfologie, en uitwisseling van sediment met de Noordzee. Rond de laatste eeuwwisseling (dus min of meer gelijktijdig met de “knik”)  is die onbalans beduidend minder (Figuur 2).
3.	De afsluting van de Zuiderzee heeft een abrupte verondieping van de geulen tot gevolg gehad. In de decennia daarna is de gemiddelde geuldiepte weer toegenomen. Rond 2000 lijkt dit te stabiliseren (Figuur 2).
 
### Hypothese

4.	Door morfologische veranderingen is de gemiddelde waterstand in de Waddenzee anders ontwikkeld dan aan de Hollandse kust. De drijvende factor daarvoor is het getij. 
 
### Analyse meetreeksen

5.	Er is een verband tussen getij (M4/M2) en gemeten waterhoogte over de tijdspanne van 1932 tot nu. Dit komt naar voren uit de Hoofdstations, omdat deze een langere meetreeks hebben. In andere stations in de Waddenzee is dit niet te zien (maar komt waarschijnlijk vooral door de relatief korte tijdreeksen). 
6.	Om de variatie binnen meetreeksen te verkleinen is gekeken naar, en gecorrigeerd voor lokaal afwijkende waarden van de verandering van zeespiegel per jaar. Als bijvangst levert dit een reeks meetjaren op die meer dan normaal afwijken. Het verdient aanbeveling om deze reeks samen met RWS te duiden. De gecorrigeerde reeksen worden nu verder bestudeerd (Figuur 3). 
 
### Theorieontwikkeling

7.	Orde-grootte schatting van veranderend getij op gemiddelde waterstand door golfvergelijking door te vertalen naar getijgolf. De analyse laat zien dat in een versimpeld estuarium, door een relatief kleine verandering van getij, een verandering van de gemiddelde waterstand in de ordegrootte van een decimeter op kan treden.
 
### Modelexperimenten

8.	Om een kwantitatief en ruimtelijk beeld te krijgen van het effect van een veranderende diepte op het getij en gemiddelde waterstand is het DCSM model gedraaid met 10 cm waterstandsverhoging op de rand (Atlantische Oceaan). Dit komt neer op een gelijkmatige verdieping van de Waddenzee van 10 cm, maar is gemakkelijker in een model te simuleren. Resultaat: Diep in de Waddenzee is de verhoging minder dan 10 cm. Hieruit concluderen we dat een verdieping van de Waddenzee mogelijk een vertraagde zeespiegelstijging tot gevolg kan hebben gehad.
9.	De verandering in getij is minder eenduidig, en daardoor moeilijker te duiden. Hier werken we nog aan.
10.	De invloed van verlaagd M2, zoals die over de laatste 2 decennia is opgetreden, is ook getest door een 4% verlanging van M2 op de rand op te leggen. De resultaten hiervan moeten nog beter worden geduid.
 
### Conclusies

11. Het is aannemelijk dat een verandering in getij kan leiden tot een verandering van de gemiddelde waterhoogte.
11.	Het is aannemelijk dat in de Waddenzee de gemiddelde waterhoogte na de afsluiting van de Zuiderzee iets heeft achtergelopen bij de Hollandse kust.
12.	De drijvende kracht, getij, is in die tijd ook veranderd. 
12. De precieze interactie tussen getij en gemiddelde waterhoogte in de Waddenzee hangt samen met de morfologie van een bekken. Denk aan het verschil tussen Westelijke Waddenzee (gedomineerd door geulen) en Oostelijke Waddenzee, grofweg tussen Lauwersoog en Eemshaven (gedomineerd door platen)


