
name: Upload to Zenodo

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  zenodo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
